### ISSUE TITLE
Data Import for Automated Scoresheet Creation

### ISSUE THREAD

**Issue by PH-Lazurous** [CIA-Homebrew/BJCP-Scoresheet#8] opened 2019-07-06 18:11 UTC
Add the ability to import data from systems like BCOEM or Reggie so that all 'base' scoresheets are created based on data from an entry vs manual creation.

**Comment by prphntm63** [comment] 2020-09-25 21:27
Duplicate of #15

**Closed by prphntm63** 2020-09-25 21:27 UTC
Labels: duplicate, enhancement
